// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

import {Script, console} from "forge-std/Script.sol";
import {CertificateRegistry} from "../src/CertificateRegistry.sol";
import {Groth16Verifier} from "../src/Groth16Verifier.sol";
import {IPoseidonT3, PoseidonT3} from "../src/PoseidonT3.sol";
import {IGroth16Verifier, PrivacyLab} from "../src/PrivacyLab.sol";
import {TrustvillePassport} from "../src/TrustvillePassport.sol";

/// Phase D6 — the Privacy Lab (module 16). Run with the DEPLOYER key:
///
///   cd contracts
///   forge script script/DeployPrivacyLab.s.sol --rpc-url didlab --account didlab-deployer \
///     --sender <deployer> --legacy --slow --gas-estimate-multiplier 115 --broadcast
///
/// Then grant STAMPER_ROLE with the ADMIN key — the script prints the exact command, and
/// the admin panel on the site can do the same thing without a private key ever leaving
/// MetaMask.
///
/// ---------------------------------------------------------------------------------------
///  THE TWO CONTRACTS NOBODY WROTE BY HAND
/// ---------------------------------------------------------------------------------------
///
/// Three contracts go out here and only one of them is ours.
///
///   PoseidonT3        circomlib's compiled hasher, deployed verbatim from embedded
///                     creation bytecode. It must hash EXACTLY as the circuit does, and a
///                     hand-written Solidity port that is subtly wrong produces proofs that
///                     verify off chain and fail on chain with nothing to point at.
///
///   Groth16Verifier   generated by snarkjs from the proving key, by ./scripts/build-circuit.sh.
///                     It is bound to ONE proving key. Rebuild the circuit and this verifier
///                     no longer accepts proofs made with the old artifacts, and vice versa —
///                     which is why the browser's .zkey and this contract have to be deployed
///                     and published together, as one change.
///
/// If Groth16Verifier.sol is missing, the circuit has not been built in this clone. Run
/// `npm run circuit` first; the deploy is meaningless without the artifacts the browser
/// fetches anyway.
contract DeployPrivacyLab is Script {
    function run() external {
        string memory path = string.concat(
            vm.projectRoot(), "/../deployments/", vm.toString(block.chainid), ".json"
        );
        string memory json = vm.readFile(path);

        address passportAddr = vm.parseJsonAddress(json, ".contracts.TrustvillePassport");
        address certsAddr = vm.parseJsonAddress(json, ".contracts.CertificateRegistry");
        require(passportAddr != address(0), "D1 not deployed: no TrustvillePassport");
        require(certsAddr != address(0), "D2b not deployed: no CertificateRegistry");

        // Reuse a hasher that is already on chain rather than paying for a second one. The
        // hasher is stateless and shared by nothing else, so one per chain is plenty.
        address existingHasher = vm.envOr("POSEIDON", address(0));

        vm.startBroadcast();

        IPoseidonT3 hasher;
        if (existingHasher == address(0)) {
            // A raw CREATE from inside a library. Foundry records it as a deployment
            // transaction the same way it records `new Contract()`, so it broadcasts
            // normally — but it is not a `new`, so `--verify` cannot guess the source and
            // the explorer will show it as unverified. That is expected: there is no
            // Solidity source for this bytecode anywhere, here or upstream.
            hasher = PoseidonT3.deploy();
        } else {
            hasher = IPoseidonT3(existingHasher);
        }

        Groth16Verifier verifier = new Groth16Verifier();

        PrivacyLab lab = new PrivacyLab(
            hasher,
            CertificateRegistry(certsAddr),
            IGroth16Verifier(address(verifier)),
            TrustvillePassport(passportAddr)
        );

        vm.stopBroadcast();

        // The constructor hashes LEVELS empty subtrees through the freshly deployed hasher.
        // If the hasher were wrong, this read would come back wrong — and every proof after
        // it would fail as UnknownRoot with no explanation. Print it so the number can be
        // compared with `zeros(0)` in app/src/zk/tree.js before anyone tries to prove
        // anything.
        console.log("");
        console.log("Empty-subtree constant (must equal ZERO in app/src/zk/tree.js):");
        console.log(lab.zeros(0));
        console.log("Opening root, with nobody enrolled:");
        console.log(lab.currentRoot());

        if (existingHasher == address(0)) {
            _record("PoseidonT3", address(hasher));
        } else {
            console.log("PoseidonT3 (reused)", address(hasher));
        }
        _record("Groth16Verifier", address(verifier));
        _record("PrivacyLab", address(lab));

        console.log("");
        console.log("NEXT, as the ADMIN. Without this the lab works but stamps no passports:");
        console.log(
            string.concat(
                "  cast send ",
                vm.toString(passportAddr),
                ' "grantRole(bytes32,address)" 0x57980102bbeb8858f40747983e69e30ef38ad79e5d2161e7bb937ea9df8528c8 ',
                vm.toString(address(lab)),
                " --rpc-url https://eth.didlab.org --legacy --interactive"
            )
        );
        console.log("  ...or the Town admin panel on the site: Passport -> STAMPER_ROLE.");

        console.log("");
        console.log("THEN, and this is not optional:");
        console.log("  1. npm run sync-abi  (the app needs PrivacyLab's ABI)");
        console.log("  2. confirm app/public/zk/ holds the SAME artifacts this verifier came");
        console.log("     from. A verifier from one build and a .zkey from another produce");
        console.log("     BadProof on every post, and the error says nothing about why.");
        console.log("  3. rebuild and deploy the site");

        console.log("");
        console.log("A reminder for whoever demonstrates this: with one member enrolled, a");
        console.log("proof of membership identifies that member. The mathematics is perfect");
        console.log("and the anonymity is zero. Enrol a class before calling it private.");
    }

    function _record(string memory name, address addr) internal {
        string memory path = string.concat(
            vm.projectRoot(), "/../deployments/", vm.toString(block.chainid), ".json"
        );
        vm.writeJson(vm.toString(addr), path, string.concat(".contracts.", name));
        vm.writeJson(vm.toString(block.timestamp), path, ".updated");
        console.log(name, addr);
    }
}
