[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "paris"   # conservative target for the DIDLab Besu chain
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "../deployments" }]

remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

[rpc_endpoints]
didlab = "https://eth.didlab.org"

[fmt]
line_length = 100
