#!/usr/bin/env node
// Copies the ABI of each contract from contracts/out into app/src/abi/generated.js,
// so the frontend never drifts from the compiled contracts.
// Run after `forge build`:  npm run sync-abi
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const NAMES = [
  'TownNoticeBoard',
  'ResidentRegistry',
  'TrustvillePassport',
  'TownToken',
  'TownBank',
  'ProductRegistry',
  'TownEscrow',
  'SealedAuction',
  'CertificateRegistry',
  'EventTickets',
  'PropertyDeeds',
  'RentEscrow',
  'VoteToken',
  'TownTreasury',
  'TownGovernor',
  'TownTimelock',
  'TownCharity',
];

const out = [
  '// GENERATED by scripts/sync-abi.mjs — do not edit by hand.',
  '// Regenerate with: cd contracts && forge build && cd .. && npm run sync-abi',
  '',
];

for (const name of NAMES) {
  const file = join(root, 'contracts/out', `${name}.sol`, `${name}.json`);
  if (!existsSync(file)) {
    console.error(`missing ${file} — run "forge build" in contracts/ first`);
    process.exit(1);
  }
  const { abi } = JSON.parse(readFileSync(file, 'utf8'));
  // Keep only what the frontend needs: functions, events and custom errors.
  const slim = abi.filter((e) => ['function', 'event', 'error'].includes(e.type));
  const key = name.charAt(0).toLowerCase() + name.slice(1) + 'Abi';
  out.push(`export const ${key} = ${JSON.stringify(slim, null, 2)};`, '');
}

const target = join(root, 'app/src/abi/generated.js');
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, out.join('\n'));
console.log(`wrote ${target} (${NAMES.length} contracts)`);
